#!/bin/bash

echo "Starting container..."

# Set environment variables
export GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP
export REACT_APP_DRUPAL_API_ENDPOINT=$REACT_APP_DRUPAL_API_ENDPOINT
export REACT_APP_PORTAL_API_ENDPOINT=$REACT_APP_PORTAL_API_ENDPOINT
export REACT_APP_IDENTITY_REDIRECT_URL=$REACT_APP_IDENTITY_REDIRECT_URL
export REACT_APP_GRAPH_API_BASE_URL=$REACT_APP_GRAPH_API_BASE_URL
export REACT_APP_IDENTITY_CLIENT_ID=$REACT_APP_IDENTITY_CLIENT_ID
export REACT_APP_IDENTITY_ISSUER_1=$REACT_APP_IDENTITY_ISSUER_1
export REACT_APP_PUBLIC_URL=$REACT_APP_PUBLIC_URL
export REACT_APP_SPARS_URL=$REACT_APP_SPARS_URL
export REACT_APP_FORUM_URL=$REACT_APP_FORUM_URL
export REACT_APP_SPARS_ADMIN=$REACT_APP_SPARS_ADMIN
export REACT_APP_NOVU_APP_ID=$REACT_APP_NOVU_APP_ID

echo "Building React app..."
npm run build

echo "Copying build to public folder..."
cp -r build/* public/

echo "Starting Node server..."
node webserver/server.js